# Homework
Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can use the instructions from 06-environment.md.

Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [1]:
import pandas as pd 

pd.__version__

'2.2.2'

Q1A: I have the 2.2.2 version of Pandas.

## Getting the data
For this homework, we'll use the Laptops Price dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [2]:
import urllib.request

url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
filename = 'laptops.csv'

urllib.request.urlretrieve(url, filename)
print(f"Downloaded {filename}")


Downloaded laptops.csv


## Q2. Records count
How many records are in the dataset?

12

1000

2160

12160

In [3]:
df = pd.read_csv('laptops.csv')

rows, columns = df.shape
print(f"Number of records (rows) in the dataset: {rows}")

Number of records (rows) in the dataset: 2160


Q2A: Since there are 2,160 rows, there are 2,160 records. 

## Q3. Laptop brands
How many laptop brands are presented in the dataset?

12

27

28

2160

In [4]:
num_brands = df['Brand'].nunique()
print(f"Number of unique laptop brands: {num_brands}")

Number of unique laptop brands: 27


Q3A: There are 27 laptop brands in the dataset.

## Q4. Missing values
How many columns in the dataset have missing values?

0

1

2

3

In [5]:
# Count the number of missing values in each column
missing_values_per_column = df.isnull().sum()

# Filter the columns with missing values (greater than 0)
columns_with_missing_values = missing_values_per_column[missing_values_per_column > 0]

# Print the number of columns with missing values
print(f"Number of columns with missing values: {len(columns_with_missing_values)}")

# Optionally, print the actual columns with missing values and their counts
print(columns_with_missing_values)

Number of columns with missing values: 3
Storage type      42
GPU             1371
Screen             4
dtype: int64


Q4A: There are 3 columns with missing values.

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

869

3691

3849

3936

In [9]:
# Filter the dataset for Dell notebooks
dell_notebooks = df[df['Brand'] == 'Dell']

# Find the maximum final price of Dell notebooks
max_price_dell = dell_notebooks['Final Price'].max()

print(f"Maximum final price of Dell notebooks: {max_price_dell}")

Maximum final price of Dell notebooks: 3936.0


Q5A: The maximum final price of Dell notebooks are $3,936.

## Q6. Median value of Screen
Find the median value of Screen column in the dataset.
Next, calculate the most frequent value of the same Screen column.
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
Now, calculate the median value of Screen once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

Yes

No

In [10]:
# 1. Find the median value of the 'Screen' column before filling missing values
initial_median = df['Screen'].median()
print(f"Initial median of 'Screen': {initial_median}")

# 2. Calculate the most frequent value (mode) of the 'Screen' column
most_frequent_screen = df['Screen'].mode()[0]
print(f"Most frequent value of 'Screen': {most_frequent_screen}")

# 3. Fill missing values in 'Screen' column with the most frequent value
df['Screen'] = df['Screen'].fillna(most_frequent_screen)

# 4. Recalculate the median value of the 'Screen' column after filling missing values
new_median = df['Screen'].median


Initial median of 'Screen': 15.6
Most frequent value of 'Screen': 15.6


Q6A: The median value of the screen did not change.

## Q7. Sum of weights
Select all the "Innjoo" laptops from the dataset.
Select only columns RAM, Storage, Screen.
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Compute the inverse of XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

0.43

45.29

45.58

91.30

In [12]:
import numpy as np

# 1. Select all "Innjoo" laptops
innjoo_laptops = df[df['Brand'] == 'Innjoo']

# 2. Select only the columns 'RAM', 'Storage', and 'Screen'
innjoo_features = innjoo_laptops[['RAM', 'Storage', 'Screen']]

# 3. Get the underlying NumPy array (X)
X = innjoo_features.values

# 4. Compute XTX (matrix-matrix multiplication between X.T and X)
XTX = X.T @ X  # Alternatively, np.dot(X.T, X)

# 5. Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# 6. Create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# 7. Multiply the inverse of XTX with the transpose of X, then multiply by y
w = XTX_inv @ X.T @ y

# 8. Compute the sum of all elements of w
w_sum = np.sum(w)
print(f"Sum of all elements of w: {w_sum}")


Sum of all elements of w: 91.2998806299555
